/*SCRIPT BORRA SCRIPT NTVC*/
/*IVAN FRANCO 17/10/2011*/

/*ELIMINO LAS TABLAS SACANDO LAS RELACIONES*/
DROP TABLE NTVC.USUARIO_ROL
DROP TABLE NTVC.USUARIO
DROP TABLE NTVC.ROL_FUNCIONALIDAD
DROP TABLE NTVC.ROL
DROP TABLE NTVC.PAGO
DROP TABLE NTVC.FUNCIONALIDAD
DROP TABLE NTVC.COMPRA
DROP TABLE NTVC.CARGA
DROP TABLE NTVC.BENEFICIARIO_POSTNET
DROP TABLE NTVC.BENEFICIARIO
DROP TABLE NTVC.TARJETA
DROP TABLE NTVC.RUBRO
DROP TABLE NTVC.POSTNET
DROP TABLE NTVC.CLIENTE
DROP TABLE NTVC.PROVINCIA

/*ELIMINO LOS STORED PROCEDURES, FUNCTION Y VIEWS*/
DROP FUNCTION NTVC.TARJETASINACTIVAS
DROP FUNCTION NTVC.CLIENTEPREMIUM
DROP PROCEDURE NTVC.ACTUALIZARPAGO
DROP PROCEDURE NTVC.CREDITOTARJETA
DROP PROCEDURE NTVC.[DNIREPETIDOS]
DROP VIEW NTVC.CLIENTE_ACTIVO
DROP VIEW NTVC.CLIENTE_INACTIVO
DROP VIEW NTVC.MONTO_TOTAL
DROP VIEW NTVC.FECHA_ULTIMA_COMPRA
DROP VIEW NTVC.DATOS_ULTIMA_COMPRA


/*ELIMINO EL SCHEMA*/
USE [GD2C2011]
GO
/****** Object:  Schema [NTVC]    Script Date: 10/17/2011 21:17:02 ******/
IF  EXISTS (SELECT * FROM sys.schemas WHERE name = 'NTVC')
DROP SCHEMA [NTVC]