/*SCRIPT BORRA SCRIPT NoTeVaConsultar*/
/*IVAN FRANCO 17/10/2011*/

/*ELIMINO LAS TABLAS SACANDO LAS RELACIONES*/
DROP TABLE NoTeVaConsultar.USUARIO_ROL
DROP TABLE NoTeVaConsultar.USUARIO
DROP TABLE NoTeVaConsultar.ROL_FUNCIONALIDAD
DROP TABLE NoTeVaConsultar.ROL
DROP TABLE NoTeVaConsultar.PAGO
DROP TABLE NoTeVaConsultar.FUNCIONALIDAD
DROP TABLE NoTeVaConsultar.COMPRA
DROP TABLE NoTeVaConsultar.CARGA
DROP TABLE NoTeVaConsultar.BENEFICIARIO_POSNET
DROP TABLE NoTeVaConsultar.BENEFICIARIO
DROP TABLE NoTeVaConsultar.TARJETA
DROP TABLE NoTeVaConsultar.RUBRO
DROP TABLE NoTeVaConsultar.POSNET
DROP TABLE NoTeVaConsultar.CLIENTE
DROP TABLE NoTeVaConsultar.PROVINCIA

/*ELIMINO EL SCHEMA*/
USE [GD2C2011]
GO
/****** Object:  Schema [NoTeVaConsultar]    Script Date: 10/17/2011 21:17:02 ******/
IF  EXISTS (SELECT * FROM sys.schemas WHERE name = 'NoTeVaConsultar')
DROP SCHEMA [NoTeVaConsultar]